config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/about', to: 'welcome#about'

  # Authentication and session management
  get '/login', to: 'github_authentication#new'
  get '/auth/github/callback', to: 'github_authentication#callback'
  get '/auth/failure', to: 'github_authentication#failure'
  delete '/logout', to: 'github_authentication#logout'

  resources :users, only: [:show] do
    resources :selections, only: %i[index create destroy]
  end

  get '/proposals/feed', to: 'proposals#feed'

  resources :proposals do
    resources :comments, only: %i[index create destroy]

    member do
      post :publish
      post :withdraw
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

require 'securerandom'

class User < ApplicationRecord
  before_save do
    email.downcase!
  end

  validates :name, presence: true
  validates :public_name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :github_uid, presence: true, uniqueness: true
  validates :github_nickname, presence: true

  has_many :proposals, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :selections, dependent: :destroy

  def self.create_with_omniauth(auth_hash)
    create! do |user|
      user.name = auth_hash[:info][:name] || auth_hash[:info][:nickname]
      user.public_name = SecureRandom.hex(7)
      user.email = auth_hash[:info][:email]
      user.github_uid = auth_hash[:uid]
      user.github_nickname = auth_hash[:info][:nickname]
    end
  end

  def block!(reason)
    update(blocked: true, block_reason: reason)
  end

  def unblock!
    update(blocked: false, block_reason: nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_mode
  before_action :correct_user, only: [:show]

  def show
  end

  private

  def check_mode
    check_mode_for_object(:user)
  end

  def correct_user
    @user = User.includes(:proposals).find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end

  def robohash_for(user, options = { size: 80 })
    robohash_id = Digest::MD5.hexdigest(user.github_uid)
    robohash_url = "https://robohash.org/#{robohash_id}?size=#{options[:size]}x#{options[:size]}"
    image_tag(robohash_url, alt: 'UIKonf Friendly Commenter', class: 'robohash')
  end

  def name_email_for(user)
    "#{user.name} <#{user.email}>"
  end
end

app/views/users/_proposal.html.erb
<a href="<%= proposal_path(proposal) %>" class="list-group-item list-group-item-action d-flex align-items-center">
  <div class="flex-fill">
    <%= proposal.title %>
  </div>
  <% if proposal.draft? %>
    <span class="badge badge-warning"><%= proposal.state %></span>
  <% elsif proposal.published? || proposal.preselected? %>
    <span class="badge badge-success"><%= proposal.state %></span>
  <% else %>
    <span class="badge badge-info"><%= proposal.state %></span>
  <% end %>
</a>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<% if @user.proposals.empty? %>
  <%= link_to 'New proposal', new_proposal_path, class: "btn btn-primary" %>
<% else %>
  <div class="d-flex align-items-center">
    <h1 class="flex-fill">Your Proposals</h1>
    <%= create_proposal_button %>
  </div>
  <ul class="list-group">
    <%= render partial: 'users/proposal', collection: @user.proposals %>
  </ul>
<% end %>

<h1>Your profiles</h1>

<div class="card border-success mb-3">
  <div class="card-header">
    Public profile
  </div>
  <div class="card-body">
    <h5 class="card-title">
      <%= @user.public_name %>
    </h5>
    <%= robohash_for @user, size: 50 %>
  </div>
</div>

<div class="card border-danger mb-3">
  <div class="card-header">
    Internal profile (only you can see this)
  </div>
  <div class="card-body">
    <h5 class="card-title">
      <%= name_email_for @user %>
    </h5>
    <%= gravatar_for @user, size: 50 %>
  </div>
</div>