config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/about', to: 'welcome#about'

  # Authentication and session management
  get '/login', to: 'github_authentication#new'
  get '/auth/github/callback', to: 'github_authentication#callback'
  get '/auth/failure', to: 'github_authentication#failure'
  delete '/logout', to: 'github_authentication#logout'

  resources :users, only: [:show] do
    resources :selections, only: %i[index create destroy]
  end

  get '/proposals/feed', to: 'proposals#feed'

  resources :proposals do
    resources :comments, only: %i[index create destroy]

    member do
      post :publish
      post :withdraw
    end
  end
end

app/models/selection.rb
class Selection < ApplicationRecord
  belongs_to :user
  belongs_to :proposal
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_mode

  LIMIT = 8

  def index
    @selections = current_user.selections
    if @selections.count > 0
      @proposals = Proposal.preselected.where("id NOT IN (?)", @selections.map { |s| s.proposal_id })
    else
      @proposals = Proposal.preselected
    end
  end

  def create
    proposal = Proposal.find(params[:proposal_id])
    unless proposal.preselected?
      flash[:error] = "You can only select a preselected proposal"
      redirect_to root_url
      return
    end

    if Selection.where(user_id: current_user.id).count >= LIMIT
      flash[:error] = "You already selected the maximum number of proposals"
      redirect_to user_selections_url(current_user)
      return
    end

    selection = current_user.selections.create(proposal: proposal)
    if selection.save
      redirect_to user_selections_url(current_user)
    else
      flash[:error] = selection.errors.full_message.to_sentence
    end
  end

  def destroy
    selection = current_user.selections.find(params[:id])
    selection.destroy
    redirect_to user_selections_url
  end

  private

  def check_mode
    check_mode_for_object(:selection)
  end
end

app/helpers/selections_helper.rb
module SelectionsHelper
  def remaining_selection_count
     SelectionsController::LIMIT - @selections.count
  end

  def maximum_reached
    SelectionsController::LIMIT == @selections.count
  end
end

app/views/selections/_proposal.html.erb
<% if can?(:create, :selection) %>
  <li class="list-group-item">
    <div class="d-flex flex-row align-items-center">
      <%= link_to proposal.title, proposal_path(proposal), class: 'flex-fill' %>
      <% if maximum_reached %>
        <button class="btn btn-outline-success" disabled>Select</button>
      <% else %>
        <%= form_with url: user_selections_path(current_user) do %>
          <%= hidden_field_tag :proposal_id, proposal.id %>
          <%= submit_tag 'Select', class: 'btn btn-outline-success' %>
        <% end %>
      <% end %>
    </div>
  </li>
<% else %>
  <%= link_to proposal.title, proposal_path(proposal), class: 'list-group-item list-group-item-action' %>
<% end %>

app/views/selections/_selection.html.erb
<% if can?(:destroy, :selection) %>
  <li class="list-group-item">
    <div class="d-flex flex-row align-items-center">
      <%= link_to selection.proposal.title, proposal_path(selection.proposal), class: 'flex-fill' %>
      <%= form_with url: user_selection_path(current_user, selection), method: :delete do %>
        <%= hidden_field_tag :proposal_id, selection.proposal.id %>
        <%= submit_tag 'Deselect', class: 'btn btn-outline-danger' %>
      <% end %>
    </div>
  </li>
<% else %>
  <%= link_to selection.proposal.title, proposal_path(selection.proposal), class: 'list-group-item list-group-item-action' %>
<% end %>

app/views/selections/index.html.erb
<% provide(:title, 'Selection') %>

<section>
  <h1>
    Your selection
  </h1>
  <p>
    You can add up to 8 proposals to your selection.
  </p>
</section>

<section>
  <% if @selections.empty? %>
    <p>
      You haven't selected any proposals yet.
    </p>
  <% else %>
    <p>
      Here are the proposals you selected:
    </p>
    <ul class="list-group">
      <%= render partial: 'selections/selection', collection: @selections %>
    </ul>
  <% end %>
</section>

<section class="mt-4">
  <p>
    Here are the proposals you can select: (<%= remaining_selection_count %> remaining)
  </p>
  <ul class="list-group">
    <%= render partial: 'selections/proposal', collection: @proposals, locals: {maximum_reached: maximum_reached} %>
  </ul>
</section>