config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/about', to: 'welcome#about'

  # Authentication and session management
  get '/login', to: 'github_authentication#new'
  get '/auth/github/callback', to: 'github_authentication#callback'
  get '/auth/failure', to: 'github_authentication#failure'
  delete '/logout', to: 'github_authentication#logout'

  resources :users, only: [:show] do
    resources :selections, only: %i[index create destroy]
  end

  get '/proposals/feed', to: 'proposals#feed'

  resources :proposals do
    resources :comments, only: %i[index create destroy]

    member do
      post :publish
      post :withdraw
    end
  end
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :selections, dependent: :destroy

  validates :user_id, presence: true
  validates :state, presence: true
  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true, length: {minimum: 200}

  default_scope { where("state != 'deleted'") }
  scope :published, -> { where(state: 'published') }
  scope :published_or_preselected, -> { where("state IN ('published', 'preselected')") }
  scope :preselected, -> { where(state: 'preselected') }
  scope :withdrawn, -> { where(state: 'withdrawn') }
  scope :without_comments_from, lambda { |user|
    if user.comments.any?
      where('proposals.id NOT IN (?)', user.comments.map(&:proposal_id).uniq)
    end
  }

  STATES = %w{draft published preselected withdrawn deleted}

  STATES.each do |state|
    define_method("#{state}?") do
      self.state == state
    end

    define_method("#{state}!") do
      self.update(state: state)
    end
  end

  def can_publish?
    %w{draft withdrawn}.include?(self.state)
  end

  def can_withdraw?
    %w{published preselected}.include?(self.state)
  end
end

app/controllers/proposals_controller.rb
# frozen_string_literal: true

class ProposalsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show feed]
  before_action :check_mode
  before_action :enforce_proposal_limit, only: %i[new create publish]
  before_action :load_proposal_for_editing, only: %i[edit update destroy publish withdraw]

  def index
    @proposals = if %i{selection refine archive}.include?(Cfp.mode.mode)
      Proposal.preselected.shuffle
    else
      Proposal.published_or_preselected.shuffle
                 end
    @withdrawn_proposals = Proposal.withdrawn
  end

  def feed
    @proposals = Proposal.published_or_preselected.last(10)
  end

  def show
    @proposal = Proposal.find(params[:id])
    if @proposal.deleted? || @proposal.draft? && !current_user?(@proposal.user)
      raise ActiveRecord::RecordNotFound
    end

    @comment = Comment.new
  end

  def new
    @proposal = Proposal.new
  end

  def create
    @proposal = current_user.proposals.create(proposal_params)
    if @proposal.save
      redirect_to @proposal
    else
      render 'new'
    end
  end

  def update
    if @proposal.update(proposal_params)
      redirect_to @proposal
    else
      render 'edit'
    end
  end

  def destroy
    @proposal.deleted!

    redirect_to proposals_path
  end

  def publish
    @proposal.published!
    flash[:success] = 'Your proposal has been published!'

    redirect_to @proposal
  end

  def withdraw
    @proposal.withdrawn!
    flash[:success] = 'Your proposal has been withdrawn!'

    redirect_to @proposal
  end

  private

  def check_mode
    check_mode_for_object(:proposal)
  end

  def proposal_params
    params.require(:proposal).permit(:title, :description)
  end

  def enforce_proposal_limit
    return if current_user.proposals.where(state: 'published').count < 3

    flash[:warning] = "You already proposed three talks. Please withdraw one first before proposing another one."
    redirect_to proposals_url
  end

  def load_proposal_for_editing
    @proposal = current_user.proposals.find_by_id(params[:id])
    return unless @proposal.nil?

    flash[:error] = 'You cannot edit proposals that are owned by other users'
    redirect_to proposals_url
  end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
  def show_comments?(proposal)
    proposal.published? || proposal.preselected?
  end

  def create_proposal_button
    if can?(:create, :proposal)
      link_to 'New Proposal', new_proposal_path, class: 'btn btn-primary'
    end
  end

  def edit_proposal_button
    if can?(:update, :proposal)
      link_to 'Edit', edit_proposal_path(@proposal), class: 'btn btn-primary'
    end
  end

  def publish_or_withdraw_proposal_button
    if @proposal.can_withdraw? && can?(:withdraw, :proposal)
      link_to 'Withdraw', withdraw_proposal_path(@proposal), method: :post, class: 'btn btn-warning', data: {confirm: 'Are you sure?'}
    elsif @proposal.can_publish? && can?(:publish, :proposal)
      link_to 'Publish', publish_proposal_path(@proposal), method: :post, class: 'btn btn-success', data: {confirm: 'Are you sure?'}
    end
  end

  def delete_proposal_button
    if can?(:destroy, :proposal)
      link_to 'Delete Forever', proposal_path(@proposal), method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure?'}
    end
  end
end

app/views/proposals/_form.html.erb
<div class="form">
  <%= form_with model: @proposal, local: true do |form| %>

    <% if @proposal.errors.any? %>
      <div id="error" class="alert alert-danger">
        <ul>
          <% @proposal.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'form-control', rows: '30' %>
      <small class="form-text text-muted">You can use markdown</small>
    </div>

    <%= form.submit class: 'btn btn-primary' %>

  <% end %>
</div>

app/views/proposals/edit.html.erb
<% provide(:title, "#{@proposal.title}") %>

<h1>Edit proposal</h1>

<%= render 'form' %>

<div class="d-flex flex-row-reverse">
  <%= delete_proposal_button %>
</div>

app/views/proposals/index.html.erb
<% provide(:title, 'Proposals') %>
<% content_for :head do %>
  <%= auto_discovery_link_tag :rss, proposals_feed_url(:format => :rss) %>
<% end %>

<div class="d-flex align-items-center">
  <h1 class="flex-fill">Proposals</h1>
  <%= create_proposal_button %>
</div>

<div class="list-group">
  <% @proposals.each do |proposal| %>
    <a href="<%= proposal_path(proposal) %>" class="d-flex align-items-center list-group-item list-group-item-action">
      <div>
        <%= proposal.title %>
      </div>
      <small class="ml-auto">
        <%= time_ago_in_words(proposal.updated_at) %> ago
      </small>
    </a>
  <% end %>
</div>

app/views/proposals/new.html.erb
<% provide(:title, 'New proposal') %>

<h1>New Proposal</h1>

<p>
  So you want to talk at UIKonf? That's awesome!
</p>
<p>
  If you haven't already, you may wish to <%= link_to 'read about the CfP process', about_path %> to find out how
  everything works.
</p>

<%= render 'form' %>

app/views/proposals/show.html.erb
<% provide(:title, "#{@proposal.title}") %>

<% if @proposal.user.blocked %>
  <div class="alert alert-danger">
    This proposal has been removed by a moderator
  </div>
<% else %>
  <% if @proposal.user == current_user %>
    <div class="alert alert-secondary d-flex flex-row align-items-center">
      <div>
        You are the author of this proposal
      </div>
      <div class="ml-auto">
        <%= edit_proposal_button %>
        <%= publish_or_withdraw_proposal_button %>
      </div>
    </div>
  <% end %>

  <% if @proposal.withdrawn? %>
    <div class="alert alert-info" role="alert">
      This proposal has been withdrawn
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-8">
      <div class="d-flex align-items-center">
        <h1>
          <%= @proposal.title %>

          <% if @proposal.user == current_user %>
          <% end %>
        </h1>
      </div>

      <p>
        <small class="ml-auto">
          Last updated: <%= time_ago_in_words(@proposal.updated_at) %> ago
        </small>
      </p>

      <%= markdown(@proposal.description) %>
    </div>
    <div class="col-sm-4">
      <% if show_comments?(@proposal) %>
        <h2>Comments</h2>
        <%= render partial: 'comments/comment', collection: @proposal.comments, locals: {author: @proposal.user} %>

        <% if logged_in? %>
          <% if can?(:create, :comment) %>
            <%= render 'comments/form' %>
          <% end %>
        <% else %>
          <%= link_to 'Log in to comment', '/auth/github', method: :post, class: 'btn btn-lg btn-primary' %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>