config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/about', to: 'welcome#about'

  # Authentication and session management
  get '/login', to: 'github_authentication#new'
  get '/auth/github/callback', to: 'github_authentication#callback'
  get '/auth/failure', to: 'github_authentication#failure'
  delete '/logout', to: 'github_authentication#logout'

  resources :users, only: [:show] do
    resources :selections, only: %i[index create destroy]
  end

  get '/proposals/feed', to: 'proposals#feed'

  resources :proposals do
    resources :comments, only: %i[index create destroy]

    member do
      post :publish
      post :withdraw
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-2">
  <div class="container d-flex">
    <div>
      The <a href="https://github.com/uikonf/cfp">CfP</a> by <a href="https://www.uikonf.com/">UIKonf</a>
    </div>
    <div class="ml-auto">
      <a href="mailto:questions@uikonf.com?subject=UIKonf CfP&body=%0D%0A%0D%0A%0D%0A---%0D%0A<%= request.original_url %>" target="_blank">Contact us</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container">
    <%= link_to 'UIKonf CfP', root_path, id: 'logo', class: 'navbar-brand' %>
    <% if Rails.env.development? %>
      <span class="badge badge-info"><%= Cfp.mode.mode %></span>
    <% end %>
    <div class="navbar-nav navbar-auto">
      <li class="nav-item"><%= link_to 'Home', root_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'About', about_path, class: 'nav-link' %></li>

      <% if can?(:index, :proposal) %>
        <li class="nav-item"><%= link_to 'Proposals', proposals_path, class: 'nav-link' %></li>
      <% end %>

      <% if logged_in? %>
        <% if can?(:index, :selection) %>
          <li class="nav-item"><%= link_to 'Selection', user_selections_path(current_user), class: 'nav-link' %></li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu">
            <%= link_to 'Profile', current_user, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Log Out', logout_path, method: :delete, class: 'dropdown-item' %>
          </div>
      <% else %>
        <% if can?(:log_in, :user) %>
          <li class="nav-item"><%= link_to 'Log In', login_path, class: 'nav-link' %></li>
        <% end %>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= yield(:head) %>
</head>

<body>

<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <%= yield %>

  <div class="pt-4">
    <%= render 'layouts/footer' %>
  </div>

  <% if Rails.env.development? %>
    <div class="alert alert-info" role="alert">
      <pre><code><%= debug(params) %></code></pre>
    </div>
  <% end %>
</div>

</body>
</html>